<?php

use App\Surah;
use Illuminate\Database\Seeder;

class SurahsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $surahs = [
        	["name" => "Al-Fatiha", "english" => "The Opening", "ayahs" => "7"],
			["name" => "Al-Baqara", "english" => "The Cow", "ayahs" => "286"],
			["name" => "Aal-e-Imran", "english" => "The family of Imran", "ayahs" => "200"],
			["name" => "An-Nisa", "english" => "The Women", "ayahs" => "176"],
			["name" => "Al-Maeda", "english" => "The Table Spread", "ayahs" => "120"],
			["name" => "Al-Anaam", "english" => "The cattle", "ayahs" => "165"],
			["name" => "Al-Araf", "english" => "The heights", "ayahs" => "206"],
			["name" => "Al-Anfal", "english" => "Spoils of war, booty", "ayahs" => "75"],
			["name" => "At-Taubah", "english" => "Repentance", "ayahs" => "129"],
			["name" => "Yunus", "english" => "Jonah", "ayahs" => "109"],
			["name" => "Hud", "english" => "Hud", "ayahs" => "123"],
			["name" => "Yusuf", "english" => "Joseph", "ayahs" => "111"],
			["name" => "Ar-Rad", "english" => "The Thunder", "ayahs" => "43"],
			["name" => "Ibrahim", "english" => "Abraham", "ayahs" => "52"],
			["name" => "Al-Hijr", "english" => "Stoneland, Rock city, Al-Hijr valley", "ayahs" => "99"],
			["name" => "An-Nahl", "english" => "The Bee", "ayahs" => "128"],
			["name" => "Al-Isra", "english" => "The night journey", "ayahs" => "111"],
			["name" => "Al-Kahf", "english" => "The cave", "ayahs" => "110"],
			["name" => "Maryam", "english" => "Mary", "ayahs" => "98"],
			["name" => "Taha", "english" => "Taha", "ayahs" => "135"],
			["name" => "Al-Anbiya", "english" => "The Prophets", "ayahs" => "112"],
			["name" => "Al-Hajj", "english" => "The Pilgrimage", "ayahs" => "78"],
			["name" => "Al-Mumenoon", "english" => "The Believers", "ayahs" => "118"],
			["name" => "An-Noor", "english" => "The Light", "ayahs" => "64"],
			["name" => "Al-Furqan", "english" => "The Standard", "ayahs" => "77"],
			["name" => "Ash-Shuara", "english" => "The Poets", "ayahs" => "227"],
			["name" => "An-Naml", "english" => "THE ANT", "ayahs" => "93"],
			["name" => "Al-Qasas", "english" => "The Story", "ayahs" => "88"],
			["name" => "Al-Ankaboot", "english" => "The Spider", "ayahs" => "69"],
			["name" => "Ar-Room", "english" => "The Romans", "ayahs" => "60"],
			["name" => "Luqman", "english" => "Luqman", "ayahs" => "34"],
			["name" => "As-Sajda", "english" => "The Prostration", "ayahs" => "30"],
			["name" => "Al-Ahzab", "english" => "The Coalition", "ayahs" => "73"],
			["name" => "Saba", "english" => "Saba", "ayahs" => "54"],
			["name" => "Fatir", "english" => "Originator", "ayahs" => "45"],
			["name" => "Ya Seen", "english" => "Ya Seen", "ayahs" => "83"],
			["name" => "As-Saaffat", "english" => "Those who set the ranks", "ayahs" => "182"],
			["name" => "Sad", "english" => "Sad", "ayahs" => "88"],
			["name" => "Az-Zumar", "english" => "The Troops", "ayahs" => "75"],
			["name" => "Ghafir", "english" => "The Forgiver", "ayahs" => "85"],
			["name" => "Fussilat", "english" => "Explained in detail", "ayahs" => "54"],
			["name" => "Ash-Shura", "english" => "Council, Consultation", "ayahs" => "53"],
			["name" => "Az-Zukhruf", "english" => "Ornaments of Gold", "ayahs" => "89"],
			["name" => "Ad-Dukhan", "english" => "The Smoke", "ayahs" => "59"],
			["name" => "Al-Jathiya", "english" => "Crouching", "ayahs" => "37"],
			["name" => "Al-Ahqaf", "english" => "The wind-curved sandhills", "ayahs" => "35"],
			["name" => "Muhammad", "english" => "Muhammad", "ayahs" => "38"],
			["name" => "Al-Fath", "english" => "The victory", "ayahs" => "29"],
			["name" => "Al-Hujraat", "english" => "The private apartments", "ayahs" => "18"],
			["name" => "Qaf", "english" => "Qaf", "ayahs" => "45"],
			["name" => "Adh-Dhariyat", "english" => "The winnowing winds", "ayahs" => "60"],
			["name" => "At-tur", "english" => "Mount Sinai", "ayahs" => "49"],
			["name" => "An-Najm", "english" => "The Star", "ayahs" => "62"],
			["name" => "Al-Qamar", "english" => "The moon", "ayahs" => "55"],
			["name" => "Al-Rahman", "english" => "The Beneficient", "ayahs" => "78"],
			["name" => "Al-Waqia", "english" => "The Event, The Inevitable", "ayahs" => "96"],
			["name" => "Al-Hadid", "english" => "The Iron", "ayahs" => "29"],
			["name" => "Al-Mujadila", "english" => "She that disputes", "ayahs" => "22"],
			["name" => "Al-Hashr", "english" => "Exile", "ayahs" => "24"],
			["name" => "Al-Mumtahina", "english" => "She that is to be examined", "ayahs" => "13"],
			["name" => "As-Saff", "english" => "The Ranks", "ayahs" => "14"],
			["name" => "Al-Jumua", "english" => "The congregation, Friday", "ayahs" => "11"],
			["name" => "Al-Munafiqoon", "english" => "The Hypocrites", "ayahs" => "11"],
			["name" => "At-Taghabun", "english" => "Mutual Disillusion", "ayahs" => "18"],
			["name" => "At-Talaq", "english" => "Divorce", "ayahs" => "12"],
			["name" => "At-Tahrim", "english" => "Banning", "ayahs" => "12"],
			["name" => "Al-Mulk", "english" => "The Sovereignty", "ayahs" => "30"],
			["name" => "Al-Qalam", "english" => "The Pen", "ayahs" => "52"],
			["name" => "Al-Haaqqa", "english" => "The reality", "ayahs" => "52"],
			["name" => "Al-Maarij", "english" => "The Ascending stairways", "ayahs" => "44"],
			["name" => "Nooh", "english" => "Nooh", "ayahs" => "28"],
			["name" => "Al-Jinn", "english" => "The Jinn", "ayahs" => "28"],
			["name" => "Al-Muzzammil", "english" => "The enshrouded one", "ayahs" => "20"],
			["name" => "Al-Muddathir", "english" => "The cloaked one", "ayahs" => "56"],
			["name" => "Al-Qiyama", "english" => "The rising of the dead", "ayahs" => "40"],
			["name" => "Al-Insan", "english" => "The man", "ayahs" => "31"],
			["name" => "Al-Mursalat", "english" => "The emissaries", "ayahs" => "50"],
			["name" => "An-Naba", "english" => "The tidings", "ayahs" => "40"],
			["name" => "An-Naziat", "english" => "Those who drag forth", "ayahs" => "46"],
			["name" => "Abasa", "english" => "He Frowned", "ayahs" => "42"],
			["name" => "At-Takwir", "english" => "The Overthrowing", "ayahs" => "29"],
			["name" => "AL-Infitar", "english" => "The Cleaving", "ayahs" => "19"],
			["name" => "Al-Mutaffifin", "english" => "Defrauding", "ayahs" => "36"],
			["name" => "Al-Inshiqaq", "english" => "The Sundering, Splitting Open", "ayahs" => "25"],
			["name" => "Al-Burooj", "english" => "The Mansions of the stars", "ayahs" => "22"],
			["name" => "At-Tariq", "english" => "The morning star", "ayahs" => "17"],
			["name" => "Al-Ala", "english" => "The Most High", "ayahs" => "19"],
			["name" => "Al-Ghashiya", "english" => "The Overwhelming", "ayahs" => "26"],
			["name" => "Al-Fajr", "english" => "The Dawn", "ayahs" => "30"],
			["name" => "Al-Balad", "english" => "The City", "ayahs" => "20"],
			["name" => "Ash-Shams", "english" => "The Sun", "ayahs" => "15"],
			["name" => "Al-Lail", "english" => "The night", "ayahs" => "21"],
			["name" => "Ad-Dhuha", "english" => "The morning hours", "ayahs" => "11"],
			["name" => "Al-Inshirah", "english" => "Solace", "ayahs" => "8"],
			["name" => "At-Tin", "english" => "The Fig", "ayahs" => "8"],
			["name" => "Al-Alaq", "english" => "The Clot", "ayahs" => "19"],
			["name" => "Al-Qadr", "english" => "The Power", "ayahs" => "5"],
			["name" => "Al-Bayyina", "english" => "The Clear proof", "ayahs" => "8"],
			["name" => "Al-Zalzala", "english" => "The earthquake", "ayahs" => "8"],
			["name" => "Al-Adiyat", "english" => "The Chargers", "ayahs" => "11"],
			["name" => "Al-Qaria", "english" => "The Calamity", "ayahs" => "11"],
			["name" => "At-Takathur", "english" => "Competition", "ayahs" => "8"],
			["name" => "Al-Asr", "english" => "The declining day", "ayahs" => "3"],
			["name" => "Al-Humaza", "english" => "The Traducer", "ayahs" => "9"],
			["name" => "Al-fil", "english" => "The Elephant", "ayahs" => "5"],
			["name" => "Quraish", "english" => "Quraish", "ayahs" => "4"],
			["name" => "Al-Maun", "english" => "Alms Giving", "ayahs" => "7"],
			["name" => "Al-Kauther", "english" => "Abundance", "ayahs" => "3"],
			["name" => "Al-Kafiroon", "english" => "The Disbelievers", "ayahs" => "6"],
			["name" => "An-Nasr", "english" => "The Succour", "ayahs" => "3"],
			["name" => "Al-Masadd", "english" => "The Flame", "ayahs" => "5"],
			["name" => "Al-Ikhlas", "english" => "Absoluteness", "ayahs" => "4"],
			["name" => "Al-Falaq", "english" => "The day break", "ayahs" => "5"],
			["name" => "An-Nas", "english" => "The mankind", "ayahs" => "6"],
        ];

        $id = 1;
        foreach ($surahs as $surah) {
        	Surah::create([
        		'id' => $id++,
        		'name' => $surah['name'],
        		'english' => $surah['english'],
        		'ayahs' => $surah['ayahs'],
        	]);
        }
    }
}
